import './globals.css'
import type { Metadata } from 'next'
import { text } from '@/fonts'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={text.className}>
      <body>
      <Providers>{children}</Providers>
      </body>
    </html>
  )
}
